# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/saurabh/Desktop/project_final_dsp/project_final_dsp.cache/wt [current_project]
set_property parent.project_path /home/saurabh/Desktop/project_final_dsp/project_final_dsp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.1 [current_project]
add_files -quiet /home/saurabh/Desktop/project_final_dsp/project_final_dsp.runs/xbip_dsp48_macro_0_synth_1/xbip_dsp48_macro_0.dcp
set_property used_in_implementation false [get_files /home/saurabh/Desktop/project_final_dsp/project_final_dsp.runs/xbip_dsp48_macro_0_synth_1/xbip_dsp48_macro_0.dcp]
add_files -quiet /home/saurabh/Desktop/project_final_dsp/project_final_dsp.runs/xbip_dsp48_macro_1_synth_1/xbip_dsp48_macro_1.dcp
set_property used_in_implementation false [get_files /home/saurabh/Desktop/project_final_dsp/project_final_dsp.runs/xbip_dsp48_macro_1_synth_1/xbip_dsp48_macro_1.dcp]
add_files -quiet /home/saurabh/Desktop/project_final_dsp/project_final_dsp.runs/xbip_dsp48_macro_2_synth_1/xbip_dsp48_macro_2.dcp
set_property used_in_implementation false [get_files /home/saurabh/Desktop/project_final_dsp/project_final_dsp.runs/xbip_dsp48_macro_2_synth_1/xbip_dsp48_macro_2.dcp]
read_verilog -library xil_defaultlib /home/saurabh/Desktop/project_final_dsp/project_final_dsp.srcs/sources_1/new/dspmatrix.v
read_xdc /home/saurabh/Desktop/project_final_dsp/project_final_dsp.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files /home/saurabh/Desktop/project_final_dsp/project_final_dsp.srcs/constrs_1/new/timing.xdc]

catch { write_hwdef -file dspmatrix.hwdef }
synth_design -top dspmatrix -part xc7z020clg484-1
write_checkpoint dspmatrix.dcp
catch { report_utilization -file dspmatrix_utilization_synth.rpt -pb dspmatrix_utilization_synth.pb }
